# .github/FUNDING.yml
github: # (leave empty unless you have GitHub Sponsors)
patreon: # (leave empty)
open_collective: # (leave empty)
ko_fi: # (leave empty)
tidelift: # (leave empty)
community_bridge: # (leave empty)
liberapay: # (leave empty)
issuehunt: # (leave empty)
otechie: # (leave empty)
custom: ["https://t.me/efikcoinofficialecosystem", "https://raw.githubusercontent.com/efikcoineternal/ECE-Wallet/main/README.md"]
